# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xibo/quicksilver/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xibo/quicksilver

PRODUCT_COPY_FILES += \
    vendor/xibo/quicksilver/proprietary/vendor/etc/bluetooth/BCM4345C5.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth/BCM4345C5.hcd \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/config.txt \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/fw_bcm43455c0_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43455c0_ag.bin \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/fw_bcm43455c0_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43455c0_ag_apsta.bin \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/fw_bcm43455c0_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43455c0_ag_p2p.bin \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/fw_bcm43456c5_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43456c5_ag.bin \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/fw_bcm43456c5_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43456c5_ag_apsta.bin \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/nvram_ap6255.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/nvram_ap6255.txt \
    vendor/xibo/quicksilver/proprietary/vendor/etc/wifi/6255/nvram_ap6256.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/nvram_ap6256.txt
PRODUCT_COPY_FILES += \
    vendor/xibo/quicksilver/proprietary/vendor/etc/tvconfig/pq/pq.db:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq.db \
    vendor/xibo/quicksilver/proprietary/vendor/etc/tvconfig/pq/pq_default.ini:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq_default.ini \
    vendor/xibo/quicksilver/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/xibo/quicksilver/proprietary/vendor/lib/hw/gralloc.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.amlogic.so \
    vendor/xibo/quicksilver/proprietary/vendor/lib/hw/hwcomposer.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.amlogic.so
